In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

## List 元素没有类型限制，效率低

In [3]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
L[0] = 100
L[5] = 'Machine Learning'
L

[100, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

## array有类型限制，效率高
没有向量、矩阵概念，也没有向量、矩阵相关的运算

In [5]:
import array

In [6]:
arr = array.array('i', [i for i in range(10)])

In [7]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[0] = 100
arr

array('i', [100, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[5] = 'Machine Learning'

TypeError: 'str' object cannot be interpreted as an integer

## numpy.array
基于array等的缺点，numpy.array应运而生

In [10]:
npArr = np.array([i for i in range(10)])
npArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
npArr[0] = 100
npArr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [12]:
npArr[5] = 'Machine Learning'

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [13]:
npArr.dtype

dtype('int64')

In [14]:
npArr[5] = 3.1415926
npArr

array([100,   1,   2,   3,   4,   3,   6,   7,   8,   9])

In [15]:
npArr2 = np.array([1, 3.1415, 5])
npArr2

array([1.    , 3.1415, 5.    ])

In [16]:
npArr2.dtype

dtype('float64')

### 创建特殊的数组
机器学习中大多数都是使用浮点型

In [17]:
# 创建10个0矩阵（数组）
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros(10).dtype

dtype('float64')

In [19]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.full((3, 5), 999)

array([[999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999]])

In [25]:
np.full(fill_value=999.0, shape=(3, 5))

array([[999., 999., 999., 999., 999.],
       [999., 999., 999., 999., 999.],
       [999., 999., 999., 999., 999.]])

## numpy.arange
i for i in range(start, end, 步长)
`[前闭后开)`

In [26]:
[i for i in range(0, 20, 3)]

[0, 3, 6, 9, 12, 15, 18]

In [27]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [28]:
[i for i in range(0, 1, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [29]:
# 支持浮点数
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [30]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### numpy.linspace
np.linspace(start, end, 几等分)

In [32]:
# 等差数列
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [33]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### numpy.random
生成相同的随机数`random.seed(int)`

In [34]:
np.random.randint(0, 10)

7

In [35]:
np.random.randint(0, 10, 10)

array([2, 6, 2, 0, 1, 4, 7, 7, 6, 3])

In [36]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
np.random.randint(2, 8, size=10)

array([5, 5, 7, 3, 3, 6, 6, 3, 4, 4])

In [38]:
np.random.randint(2, 8, size=(3, 5))

array([[6, 6, 4, 3, 4],
       [2, 3, 5, 5, 3],
       [3, 2, 2, 5, 3]])

In [39]:
np.random.seed(555)
np.random.randint(2, 8, size=(3, 5))

array([[4, 3, 3, 6, 7],
       [3, 7, 2, 7, 2],
       [6, 7, 4, 7, 5]])

In [40]:
#生成相同的随机数
np.random.seed(555)
np.random.randint(2, 8, size=(3, 5))

array([[4, 3, 3, 6, 7],
       [3, 7, 2, 7, 2],
       [6, 7, 4, 7, 5]])

In [42]:
np.random.random(5)

array([0.30725432, 0.79887295, 0.02267435, 0.64706719, 0.76878283])

In [43]:
np.random.random()

0.8926319035976734

In [44]:
np.random.random((3, 5))

array([[0.82475265, 0.56296713, 0.20633491, 0.51901626, 0.21315057],
       [0.70473498, 0.63847195, 0.71946907, 0.73001423, 0.81556019],
       [0.28162259, 0.07498055, 0.44002636, 0.87624011, 0.38040866]])

In [45]:
# 均值为0方差为1的浮点数
np.random.normal()

0.3967117988465474

In [48]:
# 均值为10方差为100的浮点数
np.random.normal(10, 100)

-125.0924461144314

In [49]:
np.random.normal(0, 1, (3, 5))

array([[-0.31320964,  0.40018891, -1.48591211,  1.01582316,  0.23602012],
       [-0.77054601, -1.12313093,  0.78717991,  0.60863098,  0.85421757],
       [ 0.08055337, -0.5072582 , -0.57151417, -0.8640132 , -0.31930666]])

In [51]:
# 查看方法文档?
np.random.normal?